---
- name: squid parse config
  command: squid -k parse

- name: squid reconfigure server
  command: squid -k reconfigure

- name: squid restart service
  service:
    name: squid
    state: restarted

- name: iptables save
  shell: iptables-save > /etc/sysconfig/iptables

- name: create squid certificate chain
  shell: "cat {{ squid_ssl_dir }}/squid.key {{squid_ssl_dir }}/squid.crt > {{ squid_ssl_dir }}/squid.pem"
  notify: squid certificate chain permissions

- name: squid certificate chain permissions
  file:
    path: "{{squid_ssl_dir}}/squid.pem"
    state: file
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
    mode: 0400

- name: Reload amazon-cloudwatch-agent
  command: "{{ cwa_agent_ctl }} -a fetch-config -m ec2 -c file:{{ cloudwatch_agent_conf_file }} -s"
  notify: Leave a copy of cw configuration
  when: ansible_virtualization_type != 'docker'

- name: Leave a copy of cw configuration
  copy:
    dest: "{{ cloudwatch_agent_conf_file }}"
    content: "{{ cloudwatch_conf }}"
    force: yes
  when: ansible_virtualization_type != 'docker'
